# Model-specific configurations

interpolation:
  method: "bilinear"
  upscale_factor: 4
  
ml_terrain:
  upscale_factor: 4
  model_type: "random_forest"
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 42
  use_terrain_features: true
  use_atmospheric_features: true
  
physics_ml:
  upscale_factor: 4
  model_type: "gradient_boosting"
  physics_weight: 0.5  # Balance between physics and ML
  n_estimators: 100
  max_depth: 5
  learning_rate: 0.1
  random_state: 42
  constraints:
    positive_definite: true
    max_daily_change: 50.0
    spatial_smoothing: 0.1
    
transformer:
  upscale_factor: 4
  architecture: "vision_transformer"
  patch_size: 2
  embed_dim: 256
  num_heads: 8
  num_layers: 6
  mlp_ratio: 4.0
  dropout: 0.1
  learning_rate: 0.0001
  weight_decay: 0.0001