# Configuration file for FWI Resolution Increase Project
# Portugal 2010-2017 Dataset

# Project paths
project:
  name: "FWI Resolution Increase"
  description: "Downscaling ERA5 FWI from 25km to 1km using self-supervised U-Net"
  author: "Master's Thesis Project"
  
# Data directories
paths:
  raw_dir: "data/raw/portugal"
  interim_dir: "data/interim/portugal"
  processed_dir: "data/processed/portugal"
  models_dir: "models"
  reports_dir: "reports"
  
  # Raw data sources
  era5_fwi: "${paths.raw_dir}/era5_fwi/FWI_25KM_MAY-NOV_2010-2017.nc"
  era5_atmospheric: "${paths.raw_dir}/era5_atmospheric"
  era5_land: "${paths.raw_dir}/era5_land"
  uerra: "${paths.raw_dir}/uerra"
  esa_landcover: "${paths.raw_dir}/esa_landcover"
  
  # Interim outputs IN CORRECT ORDER
  master_grid: "${paths.interim_dir}/01_master_grid_1km.nc"
  processed_fwi: "${paths.interim_dir}/02_processed_fwi_1km.nc"
  processed_era5_land: "${paths.interim_dir}/03_processed_era5_land_1km.nc"
  processed_era5_atmos: "${paths.interim_dir}/04_processed_era5_atmospheric_1km.nc"
  processed_uerra: "${paths.interim_dir}/05_processed_uerra_1km.nc"
  processed_landcover: "${paths.interim_dir}/06_landcover_fractions_1km.nc"
  unified_unnormalized: "${paths.interim_dir}/07_fwi_unified_unnormalized.nc"
  normalization_stats: "${paths.interim_dir}/normalization_stats.nc"
  
  # Final output
  final_normalized_dataset: "${paths.processed_dir}/fwi_unified_normalized_2010-2017.nc"

# Geographic parameters
geography:
  # Portugal bounding box
  lat_min: 36.0
  lat_max: 42.5
  lon_min: -10.0
  lon_max: -6.0
  
  # Grid resolutions
  target_resolution: 0.01  # ~1km

# Temporal parameters
temporal:
  start_date: "2010-05-01"
  end_date: "2017-11-30"
  fire_season_months: [5, 6, 7, 8, 9, 10, 11]

# Variables configuration
variables:
  target: "fwi"
  
  era5_atmospheric:
    - "t2m"
    - "tp"
    - "u10"
    - "v10"
    - "d2m"
  
  era5_land:
    - "t2m"
    - "d2m"
    - "u10"
    - "v10"
    - "tp"
    
  uerra:
    - "t2m"
    - "r2"
    - "si10"

# Model parameters
model:
  architecture: "unet"
  
  unet:
    depth: 4
    initial_filters: 64
    
# Training parameters
training:
  batch_size: 8
  learning_rate: 0.0001
  epochs: 100
  
  loss_weights:
    reconstruction: 1.0
    conservation: 0.5
    smoothness: 0.1
    
  cv_blocks:
    northwest: 
      lat: [40.5, 42.5]
      lon: [-10.0, -8.0]
    northeast:
      lat: [40.5, 42.5]
      lon: [-8.0, -6.0]
    southwest:
      lat: [36.0, 40.5]
      lon: [-10.0, -8.0]
    southeast:
      lat: [36.0, 40.5]
      lon: [-8.0, -6.0]

# Evaluation metrics
evaluation:
  primary_metric: "back_aggregation_correlation"
  success_threshold: 0.6
  
  pedrogao_grande:
    date: "2017-06-17"
    location: [40.0, -8.2]
    fwi_threshold: 30